title: Zulfah # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello My name is Zulfa I am a student from Mercu Buana University, Jakarta
  <br><br>
  Now I'm Following Independent Study With Data Analytics Concentration
  <br><br>
  <a href="https://www.linkedin.com/in/zul-fah-244990229//">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.instagram.com/zullfah_/">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
